apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: property-digest-data
  namespace: property-digest
spec:
  accessModes:
    - ReadWriteOnce         # SQLite is single-node
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: property-digest-logs
  namespace: property-digest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
