apiVersion: v1
kind: Service
metadata:
  name: property-digest
  namespace: property-digest
  labels:
    app: property-digest
spec:
  type: ClusterIP
  selector:
    app: property-digest
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
